name: Alliance-Covenant
favicon: null
layout_spectrum: 0.312662317417562
typography_spectrum: 0.36892520636320114
title: Alliance-Covenant | To Serve God.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5647430988028646
  lightness: 0.4185354409273714
  saturation: 0.31123349838890135
  rhythmicContrast: 0.38040906516835093
purpose: []
