name: Alliance-Covenant
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50264
title: Alliance-Covenant | To Serve God.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f529f'
    - '#080f00'
    - '#f9d5df'
    - '#d897db'
    - '#a16cc8'
  brandStrength: 0.5647430988028646
  lightness: 0.4185354409273714
  saturation: 0.31123349838890135
  rhythmicContrast: 0.38040906516835093
purpose: []
